disabled_rules: # rule identifiers turned on by default to exclude from running
  - block_based_kvo
  - identifier_name

# <swiftlint:disable file_length> is applied in PerseusDarkModeSingle.swift

large_tuple:
  warning: 4
  error: 5

reporter: "xcode" # reporter type
