disabled_rules: # rule identifiers turned on by default to exclude from running
  - statement_position
  - line_length
  - file_length
  - large_tuple
  - force_cast
  - identifier_name
  - opening_brace
  - colon
  - block_based_kvo
